AWSTemplateFormatVersion: "2010-09-09"
Description: "Landing Zone Stack: Organization"

Resources:
  Organization:
    Type: AWS::Organizations::Organization
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FeatureSet: ALL

  CoreOu:
    Type: AWS::Organizations::OrganizationalUnit
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: Core
      ParentId: !Ref Organization

  WorkloadOu:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: Workload
      ParentId: !Ref Organization

Outputs:
  OrganizationId:
    Description: "The ID of the AWS Organization"
    Value: !GetAtt Organization.Id

  OrganizationRootId:
    Description: "The ID of the AWS Organization Root"
    Value: !GetAtt Organization.RootId

  CoreOuId:
    Description: "The ID of the Core Organizational Unit"
    Value: !Ref CoreOu

  WorkloadOuId:
    Description: "The ID of the Workload Organizational Unit"
    Value: !Ref WorkloadOu