AWSTemplateFormatVersion: "2010-09-09"
Description: "Landing Zone Stack"

Parameters:
  LogArchiveCoreAccountEmail:
    Type: String
    Description: "Email address for the Log Archive core account"

  SecurityCoreAccountEmail:
    Type: String
    Description: "Email address for the Security core account"

  ToolingCoreAccountEmail:
    Type: String
    Description: "Email address for the Tooling core account"

  ProductionWorkloadAccountEmail:
    Type: String
    Description: "Email address for the Production Workload account"

  StagingWorkloadAccountEmail:
    Type: String
    Description: "Email address for the Staging Workload account"

Resources:
  OrganizationStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./stacks/organization.yaml 

  AccountsStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./stacks/accounts.yaml
      Parameters:
        CoreOuId: !GetAtt OrganizationStack.Outputs.CoreOuId
        WorkloadOuId: !GetAtt OrganizationStack.Outputs.WorkloadOuId
        LogArchiveCoreAccountEmail: !Ref LogArchiveCoreAccountEmail
        SecurityCoreAccountEmail: !Ref SecurityCoreAccountEmail
        ToolingCoreAccountEmail: !Ref ToolingCoreAccountEmail
        ProductionWorkloadAccountEmail: !Ref ProductionWorkloadAccountEmail
        StagingWorkloadAccountEmail: !Ref StagingWorkloadAccountEmail